name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/java-agent:2.0.0
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Build Java Application
      run: kube-pet-clinc-app/mvn clean install -DskipTests

    - name: Build Docker image
      run: |
        kube-pet-clinc-app/docker build -t pet-clinic:1.0.0 .

    - name: Command
      run: |
        kubectl version

    - name: Create Namespace if not exists
      run: |
        kubectl create namespace pet-clinic-app || true
        kubectl create namespace pet-clinic-db || true

    - name: Deploy MySQL Database
      run: |
        kubectl apply -f deployment/secret.yml --namespace=pet-clinic-db
        kubectl apply -f deployment/mysql/configmap.yml
        kubectl apply -f deployment/mysql/mysql.yml

    - name: Deploy Java Application
      run: |
        kubectl apply -f deployment/secret.yml --namespace=pet-clinic-app
        kubectl apply -f deployment/java-app/configmap.yml
        kubectl apply -f deployment/java-app/java.yml