name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: test_runner
    container:
      image: techiescamp/java-agent:2.0.0

    steps:

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build and Push Image to ECR
      env:
        IMAGE_NAME: pet-clinic
        TAG: 6.0.0
        DOCKERFILE: ./Dockerfile
        ECR_REGISTRY: 814200988517.dkr.ecr.us-west-2.amazonaws.com
        ECR_REPOSITORY: pet-clinic
        IMAGE_TAG: 6.0.0
      run: |
        echo "Building and pushing Docker image..."
        # Example command to run Kaniko and push to ECR
        /kaniko-project/executor --context . --dockerfile ${DOCKERFILE} --destination ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} --use-new-run