name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/jdk-17:1.0.0
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        repository: kubernetes-learning-projects/kube-petclinc-app
        ref: main

    - name: Build Java Application
      run: mvn clean install -DskipTests
