name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/java-agent:2.0.0
    steps:
    - name: Checkout source code Repository
      uses: actions/checkout@v2
      with:
        repository: kubernetes-learning-projects/kube-petclinc-app
        ref: main
    
    - name: Copy Deployment Files to Workspace
      run: |
        mkdir -p $GITHUB_WORKSPACE/deployment
        cp -r * $GITHUB_WORKSPACE

    - name: Command
      run: |
        ls
