name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  kaniko-build:
    runs-on: arc-runner-set
    container:
      image: techiescamp/java-agent:3.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: kubernetes-learning-projects/helm-chart
          ref: main

      - name: Check
        run: ls

      - name: Update Image Tag Values
        run: |
          chart_dir="java-app"
          new_image_tag=3.0.0
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values-dev.yaml"
    
      - name: Commit the changes made
        run: | 
          git config --global user.name 'aswin-vijayan'
          git config --global user.email 'aswinvj390@gmail.com'
          git commit -am "updating image tag"
          git push

