name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/java-agent:2.0.0
    steps:
    - name: Checkout source code Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Checkout source code Repository
      run: git clone https://github.com/kubernetes-learning-projects/kube-petclinc-app.git

    - name: Command
      run: |
        ls

    - name: Build Java Application
      run: mvn -f kube-pet-clinic-app clean install -DskipTests

