name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: test_runner
    container:
      image: techiescamp/java-agent:3.0.0

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build image with Kaniko
        uses: addnab/docker-run-action@v3
        with:
          image: gcr.io/kaniko-project/executor:latest
          run: |
            sh -c /kaniko/executor \
              --context git://github.com/kubernetes-learning-projects/kube-petclinc-app \
              --dockerfile /Dockerfile.test \
              --destination 814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:6.0.0