name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/java-agent:1.0.0

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: kubernetes-learning-projects/kube-petclinc-app
          ref: main

      - name: Perform ls and pwd
        run: |
          ls -al
          pwd

      - name: Build Java Application
        run: mvn clean install -DskipTests

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker run --rm \
          -v $(pwd):/workspace \
          gcr.io/kaniko-project/executor:latest \
          --context=dir:///workspace \
          --dockerfile=/workspace/Dockerfile \
          --destination=814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:5.0.0