name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/java-agent:1.0.0

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: kubernetes-learning-projects/kube-petclinc-app
          ref: main

      - name: Build Java Application
        run: mvn clean install -DskipTests

      - name: Build and push Docker image to ECR
        uses: GoogleContainerTools/kaniko-action@v1
        with:
          context: .
          dockerfile: ./dockerfile
          destination: 814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:5.0.0
          args: >
            --dockerfile=PATH_TO_YOUR_DOCKERFILE_DIRECTORY/Dockerfile
            --context=dir://$(PWD)
            --destination=814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:5.0.0
