name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  kaniko-build:
    runs-on: arc-runner-set
    container:
      image: techiescamp/java-agent:3.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: kubernetes-learning-projects/helm-chart
          ref: main

      - name: Check
        run: ls

      - name: Update Image Tag Values
        run: |
          chart_dir="java-app"
          new_image_tag=3.0.0
          sed -i "s/^\(\s*\)tag: .*/\1tag: $new_image_tag/" "$chart_dir/values-dev.yaml"
      
      - name: view
        run: |
          echo "${{ secrets.TOKEN }}"
          echo "${{ secrets.USERNAME }}"
          echo "${{ secrets.USERNAME }}"

      - name: Commit the changes made
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.USERNAME }}"
          git add .
          git commit -m "updating image tag"
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git push


