name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/java-agent:2.0.0
    steps:
    - name: Checkout Source Code Repository
      uses: actions/checkout@v2
      with:
        repository: kubernetes-learning-projects/kube-petclinc-app
        ref: main

    - name: Checkout Actions Repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Command
      run: |
        ls
        ls kube-petclinc-app

    - name: Create Namespace if not exists
      run: |
        kubectl create namespace pet-clinic-app || true
        kubectl create namespace pet-clinic-db || true

    - name: Deploy MySQL Database
      run: |
        kubectl apply -f deployment/secret.yml --namespace=pet-clinic-db
        kubectl apply -f deployment/mysql/configmap.yml
        kubectl apply -f deployment/mysql/mysql.yml

    - name: Deploy Java Application
      run: |
        kubectl apply -f deployment/secret.yml --namespace=pet-clinic-app
        kubectl apply -f deployment/java-app/configmap.yml
        kubectl apply -f deployment/java-app/java.yml