name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: test_runner
    container:
      image: techiescamp/java-agent:3.0.0

    steps:

      - name: Stress the pod
        run: |
          apt-get update && apt-get install -y stress
          stress --cpu 8 --io 4 --vm 2 --vm-bytes 128M --timeout 300s
