name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  app-build:
    runs-on: arc-runner-set
    container:
      image: ubuntu:latest

    steps:

    - name: Sleep
      run: sleep 5m

  kaniko-build:
    runs-on: arc-runner-set
    container:
      image: ubuntu:latest

    steps:

      - name: Sleep
        run: sleep 5m
