name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: test_runner
    container:
      image: techiescamp/java-agent:3.0.0

    steps:
      - name: CLI
        run: |
          aws ecr describe-repositories
