name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  kaniko-build:
    runs-on: arc-runner-set
    container:
      image: techiescamp/github-actions:2.0.0

    steps:

      - name: test
        run: |
          ls
          pwd

      - name: Build and push container test
        run: |
          /kaniko/executor --dockerfile="/Dockerfile.test" \
            --context="git://github.com/kubernetes-learning-projects/kube-petclinc-app" \
            --destination="814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:5.0.0"