name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set
    container:
      image: techiescamp/java-agent:1.0.0

    steps:
      - name: Wait for 5 minutes
        run: sleep 5m
