name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: eks_runner
    container:
      image: techiescamp/java-agent:2.0.0

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: kubernetes-learning-projects/kube-petclinc-app
          ref: main

      - name: Build Java Application
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: |
          docker build -t pet-clinic:1.0.0 .

      - name: Push image to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 814200988517.dkr.ecr.us-west-2.amazonaws.com
          docker tag pet-clinic:1.0.0 814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:1.0.0
          docker push 814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:1.0.0
        env:
          AWS_REGION: us-west-2
          AWS_DEFAULT_REGION: us-west-2
          AWS_ACCOUNT_ID: 814200988517
