name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  docker-build:
    runs-on: arc-runner-set
    container:
      image: gcr.io/kaniko-project/executor:debug

    steps:

      - name: Build and push container test
        run: |
          /kaniko/executor --dockerfile="/Dockerfile" \
            --context="git://github.com/kubernetes-learning-projects/github-actions" \
            --destination="814200988517.dkr.ecr.us-west-2.amazonaws.com/dev:1.0.${{ github.run_number }}"
    
  change-manifest:
    runs-on: arc-runner-set
    container:
      image: techiescamp/java-agent:3.0.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: kubernetes-learning-projects/helm-chart
          token: ${{ secrets.GIT_TOKEN }}

      - name: Check
        run: ls

      - name: Update Image Tag Values
        run: |
          chart_dir="nginx"
          new_image_tag=1.0.${{ github.run_number }}
          sed -i "s/^\(\s*\)tag: .*/\1tag: $new_image_tag/" "$chart_dir/values.yaml"
      
      - name: Commit the changes made
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add .
          git commit -m "updating image tag 1.0.${{ github.run_number }}"
          git push origin main
