name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: test_runner
    container:
      image: techiescamp/java-agent:2.0.0

    steps:

      - name: Build Docker Image
        run: |
          docker run --rm \
          gcr.io/kaniko-project/executor:latest \
          --context=git://github.com/kubernetes-learning-projects/kube-petclinc-app \
          --dockerfile=/Dockerfile.test \
          --destination=814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic