name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner
    container:
      image: gcr.io/kaniko-project/executor:v1.20.1-debug

    steps:
      # - name: List ECR Repositories
      #   run: |
      #     aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 814200988517.dkr.ecr.us-west-2.amazonaws.com

      # - name: Sleep
      #   run: sleep 10m
      - name: Build and push container test
        run: |
          /kaniko/executor --dockerfile="/Dockerfile.test" \
            --context="git://github.com/kubernetes-learning-projects/kube-petclinc-app" \
            --destination="814200988517.dkr.ecr.us-west-2.amazonaws.com/pet-clinic:6.0.0"
