name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  app-build:
    runs-on: arc-runner-set
    
    steps:
    - name: Run containers in parallel
      run: |
        docker run -d --name container1 alpine sleep 600 &
        docker run -d --name container2 alpine sleep 600 &
        docker run -d --name container3 alpine sleep 600 &
        wait
