name: Build and Deploy

on:
  push:
    branches:
      - main


jobs:
  docker-build:
    runs-on: arc-runner-set
    container:
      image: techiescamp/java-agent:3.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -f test:1.0 -t Dockerfile .

      - name: push
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 814200988517.dkr.ecr.<region>.amazonaws.com
          docker tag test:1.0 814200988517.dkr.ecr.us-west-2.amazonaws.com/dev:1.0
          docker push 814200988517.dkr.ecr.us-west-2.amazonaws.com/dev:1.0

